// <auto-generated />
using System;
using DinarInvestments.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DinarInvestments.Infrastructure.Migrations
{
    [DbContext(typeof(InvestorDbContext))]
    partial class InvestorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DinarInvestments.Domain.Models.Investment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("InvestmentOpportunityId")
                        .HasColumnType("integer");

                    b.Property<long>("InvestorId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentOpportunityId");

                    b.HasIndex("InvestorId");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("DinarInvestments.Domain.Models.InvestmentOpportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinimumInvestmentAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("InvestmentOpportunities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 7, 14, 19, 52, 1, 463, DateTimeKind.Utc).AddTicks(9540),
                            MinimumInvestmentAmount = 1000m,
                            Name = "Real Estate Fund"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 7, 14, 19, 52, 1, 464, DateTimeKind.Utc).AddTicks(300),
                            MinimumInvestmentAmount = 500m,
                            Name = "Tech Growth Fund"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 7, 14, 19, 52, 1, 464, DateTimeKind.Utc).AddTicks(300),
                            MinimumInvestmentAmount = 250m,
                            Name = "SME Sukuk"
                        });
                });

            modelBuilder.Entity("DinarInvestments.Domain.Models.Investor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("DinarInvestments.Domain.Models.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("FromWalletId")
                        .HasColumnType("uuid");

                    b.Property<long>("InvestorId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ToWalletId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FromWalletId");

                    b.HasIndex("InvestorId");

                    b.HasIndex("ToWalletId");

                    b.HasIndex("TransactionReference")
                        .IsUnique()
                        .HasDatabaseName("IX_Transaction_TransactionReference");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("DinarInvestments.Domain.Models.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<long>("InvestorId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvestorId");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("DinarInvestments.Domain.Models.Investment", b =>
                {
                    b.HasOne("DinarInvestments.Domain.Models.InvestmentOpportunity", null)
                        .WithMany()
                        .HasForeignKey("InvestmentOpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DinarInvestments.Domain.Models.Investor", null)
                        .WithMany("Investments")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DinarInvestments.Domain.Models.Transaction", b =>
                {
                    b.HasOne("DinarInvestments.Domain.Models.Wallet", null)
                        .WithMany()
                        .HasForeignKey("FromWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DinarInvestments.Domain.Models.Investor", null)
                        .WithMany("Transactions")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DinarInvestments.Domain.Models.Wallet", null)
                        .WithMany()
                        .HasForeignKey("ToWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DinarInvestments.Domain.Models.Wallet", b =>
                {
                    b.HasOne("DinarInvestments.Domain.Models.Investor", null)
                        .WithMany("Wallets")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DinarInvestments.Domain.Models.Investor", b =>
                {
                    b.Navigation("Investments");

                    b.Navigation("Transactions");

                    b.Navigation("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
